### ISSUE TITLE
Can't get 0.4 to work

### ISSUE THREAD

**Issue by kwoot** [EU-EDPS/website-evidence-collector#27]
Interesting project. Now if only I could get it to work...

$ npm install chromium

> chromium@2.1.2 postinstall EU-EDPS-website-evidence-collector-9fd16aa/node_modules/chromium
> node install.js

Step 1. Retrieving Chromium latest revision number
Step 2. Downloading Chromium (this might take a while). Revision number: 757044
Step 3. Setting up Chromium binaries
Process is successfully finished
+ chromium@2.1.2
added 25 packages from 15 contributors and audited 457 packages in 17.359s
found 0 vulnerabilities

$ website-evidence-collector https://www.nu.nl
(node:19864) UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Launcher.js:236:15)
    at module.exports.launch (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Puppeteer.js:40:27)
    at /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js:69:35
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js:580:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
(node:19864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rriemann-eu** [comment]
Dear @kwoot,

both readme.md and FAQ.md here on Github contain advice for the installation of the website evidence collector. However, there is at no time a need to call `npm install chromium`.

If you need support for the installation, please check first those two files for advice, check if the solution to #5 helps you also. If not, please report back with more details on your platform and the precise steps you have undertaking for the installation so far.

**Comment by jalemann** [comment]
The solution provided in https://github.com/EU-EDPS/website-evidence-collector/issues/5 worked for me.

**Comment by rriemann-eu** [comment]
I'll close this issue. Please re-open if issue persists in the current testing version (master branch).
