### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Protocol error (Performance.enable): Target closed.

### ISSUE THREAD

**Issue by jasmines** [EU-EDPS/website-evidence-collector#73]
(node:9856) UnhandledPromiseRejectionWarning: Error: Protocol error (Performance.enable): Target closed.
    at /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._initialize (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Page.js:136:20)
    at Function.create (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Page.js:47:16)
    at /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:311:19)
    at async Promise.all (index 0)
  -- ASYNC --
    at Target.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:314:35
    at Array.map (<anonymous>)
    at BrowserContext.pages (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:314:14)
    at BrowserContext.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:112:23)
    at /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:233:90
    at Array.map (<anonymous>)
    at Browser.pages (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:233:67)
    at Browser.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:112:23)
    at /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js:134:31
  -- ASYNC --
    at BrowserContext.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:233:90
    at Array.map (<anonymous>)
    at Browser.pages (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Browser.js:233:67)
    at Browser.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:112:23)
    at /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js:134:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:9856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rriemann** [comment]
Dear @jasmines ,

Thank you for your interest in the Website Evidence Collector. The EDPS can only provide support on an best-effort basis. To reproduce your issue, you would need to provide more details, such as the command that you used for scanning and possibly the website. Also the precise software version of nodejs and the Website Evidence Collector are relevant.
