### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by StefanKBa** [EU-EDPS/website-evidence-collector#82]
(with a fresh install of tarball/master  on latest ubuntu ) 

website-evidence-collector --no-output --yaml https://www.edps.eu
/usr/local/lib/node_modules/website-evidence-collector/lib/setup-beacon-recording.js:97
            fileName: request.frame()?.url(),
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/collector/browser-session.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

---
I would point to the double ".." at Object.Module._extensions..js   ?

**Comment by StefanKBa** [comment]
Actually already happens like this. - Fresh install.. :-(

website-evidence-collector
/usr/local/lib/node_modules/website-evidence-collector/lib/setup-beacon-recording.js:97
            fileName: request.frame()?.url(),
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/collector/browser-session.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by rriemann** [comment]
Can you please tell me which version of node you are using?

    node --version

When I run `website-evidence-collector --no-output --yaml https://www.edps.eu` on master (commit b77661da2693cb242b84ddfc4ca526e91a341da6) with node v17.7.1, then I get the YAML output followed by another error:

~~~
[…]
websockets: {}
start_time: 2022-09-26T11:54:58.974Z
end_time: 2022-09-26T11:55:11.351Z
websocketLog: {}

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at Object.c.convertHtmlToPdf (/EDPS/website-evidence-collector/reporter/index.js:81:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/EDPS/website-evidence-collector/index.js:95:3)
    at async /EDPS/website-evidence-collector/bin/website-evidence-collector.js:26:3 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.7.1
~~~

**Comment by StefanKBa** [comment]
node --version
v12.22.9

**Comment by StefanKBa** [comment]
Solved my issue - which was the old outdated nodejs packaged with Ubuntu LTS releases

Fixed by:
    cd ~
    curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
    less nodesource_setup.sh
    sudo npm uninstall --global website-evidence-collector

    sudo apt remove nodejs
    sudo bash nodesource_setup.sh
    sudo apt-get install -y nodejs
    sudo apt autoremove
    sudo apt-get update
    sudo apt-get install -y nodejs
    node -v
    sudo npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master

and it works:
    website-evidence-collector --no-output --yaml https://example.com 2> /dev/null
