### ISSUE TITLE
Errors thrown - when Page returns a 404 (within an actual page with cookies, etc)

### ISSUE THREAD

**Issue by StefanKBa** [EU-EDPS/website-evidence-collector#83]
{"level":"info","message":"browsing now to https://www.SOMESITE.com/index.html/SOMETHING/bh","timestamp":"2022-09-28T11:24:08.497Z","type":"Browser"}
{"level":"debug","message":"Failed to load resource: the server responded with a status of 404 ()","timestamp":"2022-09-28T11:24:08.670Z","type":"Browser.Console"}
{"data":{"filter":"/eu_cookie_$script","listName":"fanboy-annoyance.txt","query":{"v":"1.4.1"},"url":"https://www.SOMESITE.com/sites/all/modules/contrib/eu_cookie_compliance/js/jquery.cookie-1.4.1.min.js?v=1.4.1"},"level":"warn","message":"Potential Tracking Beacon captured via fanboy-annoyance.txt with endpoint https://www.SOMESITE.com/sites/all/modules/contrib/eu_cookie_compliance/js/jquery.cookie-1.4.1.min.js.","stack":[{"fileName":"https://www.SOMESITE.com/index.html/SOMETHING/bh","source":"requested from https://www.SOMESITE.com/index.html/SOMETHING/bh and matched with fanboy-annoyance.txt filter /eu_cookie_$script"}],"timestamp":"2022-09-28T11:24:08.800Z","type":"Request.Tracking"}
{"level":"debug","message":"JQMIGRATE: Migrate is installed, version 1.4.1","timestamp":"2022-09-28T11:24:10.268Z","type":"Browser.Console"}
{"data":{"modernizr":"modernizr"},"level":"warn","location":"https://www.SOMESITE.com/index.html/SOMETHING/bh","message":"LocalStorage filled with key(s) modernizr for origin https://www.SOMESITE.com.","origin":"https://www.SOMESITE.com","raw":{"modernizr":"modernizr"},"stack":[{"columnNumber":7300,"fileName":"https://www.SOMESITE.com/sites/all/themes/SOMECOMPANY_us/scripts/modernizr.js?riuwsq","functionName":"C.localstorage","lineNumber":1,"source":"    at C.localstorage (https://www.SOMESITE.com/sites/all/themes/SOMECOMPANY_us/scripts/modernizr.js?riuwsq:1:7300)"},{"columnNumber":8081,"fileName":"https://www.SOMESITE.com/sites/all/themes/SOMECOMPANY_us/scripts/modernizr.js?riuwsq","lineNumber":1,"source":"    at https://www.SOMESITE.com/sites/all/themes/SOMECOMPANY_us/scripts/modernizr.js?riuwsq:1:8081"}],"timestamp":"2022-09-28T11:24:10.430Z","type":"Storage.LocalStorage"}
/usr/lib/node_modules/website-evidence-collector/lib/setup-cookie-recording.js:227
      while (frame.parentFrame()) {
                   ^

TypeError: Cannot read properties of null (reading 'parentFrame')
    at /usr/lib/node_modules/website-evidence-collector/lib/setup-cookie-recording.js:227:20
    at /usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Page.emit (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:187:25
    at /usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at NetworkManager.emit (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)

Node.js v18.9.1

**Comment by rriemann** [comment]
Do you have this problem with all websites?

If not, how can I reproduce this problem?

**Comment by StefanKBa** [comment]
Give me some time to replicate.
