### ISSUE TITLE
SOLVED - Error: Could not find Chrome (ver. 117.0.5938.92).

### ISSUE THREAD

**Issue by StefanKBa** [EU-EDPS/website-evidence-collector#98]
All worked nicely before.. - now after:  sudo npm install --global ./website-evidence-collector-2.1.1.tar.gz

----
$ website-evidence-collector --no-output --yaml https://joinup.ec.europa.eu/
/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298
                    throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chrome (ver. 117.0.5938.92). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/testus/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27)
    at ChromeLauncher.executablePath (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:191:25)
    at ChromeLauncher.computeLaunchArguments (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:98:37)
    at async ChromeLauncher.launch (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
    at async Object.createBrowserSession (/usr/lib/node_modules/website-evidence-collector/collector/browser-session.js:35:19)
    at async c.createSession (/usr/lib/node_modules/website-evidence-collector/collector/index.js:29:24)
    at async run (/usr/lib/node_modules/website-evidence-collector/index.js:22:3)
    at async /usr/lib/node_modules/website-evidence-collector/bin/website-evidence-collector.js:19:3

Node.js v18.17.1

**Comment by StefanKBa** [comment]
fixed.. - 
DO NOT RUN: sudo npm install --global ./website-evidence-collector-2.1.1.tar.gz
Instead follow the actual instructions ;-) : 

1. npm install --global ./website-evidence-collector-2.1.1.tar.gz
2. mkdir "${HOME}/.npm-packages"
3. npm config set prefix "${HOME}/.npm-packages"
4. npm install --global ./website-evidence-collector-2.1.1.tar.gz



--
I also updated the chrome and chromedriver manually as per  https://developer.chrome.com/blog/chrome-for-testing/ - but assume that the npm install actually takes care of that... 

- npx @puppeteer/browsers install chrome@stable
- npx @puppeteer/browsers install chromedriver@stable

**Comment by StefanKBa** [comment]
closed
